blog/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = [
	url(r'^$', views.BlogIndex.as_view(), name="index"),
	url(r'^userauth/', views.userauth, name="userauth"),
	url(r'^feed/$', views.BlogFeed.as_view(), name="feed"),
	url(r'^post/(?P<slug>\S+)$', views.BlogDetail.as_view(), name="post_detail"),
]

herokuapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('blog.urls', namespace='blog')),
    url(r'^blog/',include('blog.urls', namespace='blog')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^markdown/', include('django_markdown.urls')),
]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Tag(models.Model):
	slug = models.SlugField(max_length=200, unique=True)

	def __str__(self):
		return self.slug

class PostQuerySet(models.QuerySet):
	def published(self):
		return self.filter(publish=True)

class Post(models.Model):
	title = models.CharField(max_length=200)
	body = models.TextField()
	slug = models.SlugField(max_length=200, unique=True)
	publish = models.BooleanField(default=False)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	tags = models.ManyToManyField(Tag)

	objects = PostQuerySet.as_manager()

	def get_absolute_url(self):
		return reverse("blog:post_detail", kwargs={"slug": self.slug})

	class Meta:
		verbose_name = "Blog Post"
		verbose_name_plural = "Blog Posts"
		ordering = ["-created"]

blog/views.py
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.views import generic
from django.contrib.auth.models import User
from . import models

# Create your views here.
def userauth(request):
	context = RequestContext(request, {'request':request, 'user':request.user})
	return render_to_response('blog/userauth.html',context_instance=context)

"""
class BlogLogin(generic.ListView):
	model = User
	template_name = "blog/login.html"
"""
class BlogFeed(generic.ListView):
	queryset = models.Post.objects.published()[:5]
	template_name = "blog/feed.html"

class BlogIndex(generic.ListView):
	queryset = models.Post.objects.published()
	template_name = "blog/home.html"

class BlogDetail(generic.DetailView):
	model = models.Post
	template_name = "blog/post.html"

blog/templates/blog/auth_base.html
<!DOCTYPE html>
<html lang="en">
 <head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>{% block title %}Yinglei's Blog{% endblock %}</title>

   <!-- Bootstrap -->
   <link href="/static/css/bootstrap.min.css" rel="stylesheet">
   <link href="/static/css/bootstrap-theme.min.css" rel="stylesheet">
   <link href="/static/css/fbposter.css" rel="stylesheet">

   <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
   <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
   <!--[if lt IE 9]>
     <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
     <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
   <![endif]-->
 </head>
 <body>
   {% block main %}{% endblock %}
   <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
   <!-- Include all compiled plugins (below), or include individual files as needed -->
   <script src="/static/js/bootstrap.min.js"></script>
 </body>
</html>

blog/templates/blog/base.html
{% load staticfiles %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load disqus_tags %}
{% disqus_dev %}
<!DOCTYPE html>
<html lang="en-US">
<body>
<!--facebook-jssdk-->
<script>
		window.fbAsyncInit = function() {
		FB.init({
		  appId      : '419114911618911',
		  xfbml      : true,
		  version    : 'v2.4'
		});
		};

		(function(d, s, id){
		 var js, fjs = d.getElementsByTagName(s)[0];
		 if (d.getElementById(id)) {return;}
		 js = d.createElement(s); js.id = id;
		 js.src = "//connect.facebook.net/en_US/sdk.js";
		 fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
</script>
<!--end of facebook-jssdk-->
<div class="navbar navbar-inverse navbar-fixed-top">
	
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	  </button>
	  <a class="navbar-brand" href="/">Keep Learning!</a>
	</div>
	<div class="container">
		<div class="collapse navbar-collapse">
		  <ul class="nav navbar-nav">
			<li class="active"><a href="/">Home</a></li>
			<li class="active"><a href="/">Projects</a></li>
			<li class="active"><a href="/">Resume</a></li>
			<li class="active"><a href="/">Contact</a></li>
		  </ul>
		  <ul class="nav navbar-nav navbar-right">
		  	<!--
			{% if user and user.is_authenticated %}
			<li class="active"><a href="{% url 'blog:userauth' %}">Logout</a></li>
			{% else %}
			<li class="active"><a href="{% url 'blog:userauth'%}">Login</a></li>
			{% endif %}
			-->
		  </ul>
		</div><!--/.nav-collapse -->
	</div>
</div><!--/.navbar -->
<hr>
<hr>
<div class="row-offcanvas row-offcanvas-left">
  <div id="sidebar" class="sidebar-offcanvas">
      <div class="col-md-3">
      	<div class="panel" align="center">
	  <iframe width="300" height="160"
	  src="https://www.youtube.com/embed/hajnEpCq5SE" frameborder="3"
	  allowfullscreen></iframe>
	</div>
        <h3>Under construction, coming soon! </h3>
        <ul class="nav nav-pills nav-stacked" align="center">
          <li class="active"><a href="/">Todo list</a></li>
        </ul>
		
      </div>
  </div>
  <div id="main">
      <div class="col-md-6">
      	  <p class="visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas"><i class="glyphicon glyphicon-chevron-left"></i></button>
          </p>
          <h2>I build reliable and complex systems.</h2>
		  <p>{% block blog_posts %}{% endblock %}</p>
		  <!--
          <div class="row">
              <div class="col-md-12"><div class="well"><p>Shrink the browser width to make the sidebar collapse off canvase.</p></div></div>
          </div>
          <div class="row">
              <div class="col-md-4"><div class="well"><p>2 cols</p></div></div>
              <div class="col-md-4"><div class="well"><p>2 cols</p></div></div>
              <div class="col-md-4"><div class="well"><p>2 cols</p></div></div>
          </div>
          <div class="row">
              <div class="col-lg-6 col-sm-6"><div class="well"><p>3 cols, 3 small cols</p></div></div>
              <div class="col-lg-6 col-sm-6"><div class="well"><p>3 cols, 3 small cols</p></div></div>
          </div>
          <div class="row">
              <div class="col-lg-4 col-sm-6"><div class="well">2 cols, 3 small cols</div></div>
              <div class="col-lg-4 col-sm-6"><div class="well">2 cols, 3 small cols</div></div>
              <div class="col-lg-4 col-sm-6"><div class="well">2 cols, 3 small cols</div></div>
          </div>
		  -->
      </div>
  </div>
  <div id="sidebar" class="sidebar-offcanvas">
      <div class="col-md-3">
        <h3>Quick Links</h3>
        <ul class="nav nav-pills nav-stacked">
			<li><a href="https://docs.djangoproject.com/en/1.8/" target="_blank">Django Documentation</a></li>
			<li><a href="https://docs.python.org/3/" target="_blank">Python Documentation</a></li>
			<li><a href="http://www.w3schools.com/html/default.asp" target="_blank">HTML, CSS and Javascript</a></li>
			<li><a href="http://guides.rubyonrails.org/getting_started.html" target="_blank">Rails Guide</a></li>
			<li><a href="#system design" target="_blank">System Design</a></li>
        </ul>
		<h3>Others</h3>
		<ul class="nav nav-pills nav-stacked">
			<li><a href="https://github.com/YingleiZhang" target="_blank">Github</a></li>
			<li><a href="https://www.linkedin.com/profile/view?id=AAIAAAawIowBh-uGBhzG5lOp0dqXfe1_Rz9SLJQ&trk=nav_responsive_tab_profile" target="_blank">Linkedin</a></li>
		</ul>
      </div>
  </div>
</div><!--/row-offcanvas -->
</body>

</html>
    

blog/templates/blog/feed.html
{% extends "blog/base.html" %}
{% load staticfiles %}

{% load django_markdown %}
		
{% block blog_posts %}
{% for object in object_list %}
  <div class = "post" >
  	 <h4><a href="{% url "blog:post_detail" slug=object.slug %}">{{ object.title }}</a></h4>
  	 <p class="meta">
  	{{ object.created }}| Tagged under {{ object.tags.all|join:", "}}
  	 </p>
  	{{ object.body|markdown }}
  </div>
{% endfor %}
{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% load disqus_tags %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}" />

{% load django_markdown %}		
{% block blog_posts %}
	{% for object in object_list %}
		<div class = "post" >
			<h4><a href="{% url "blog:post_detail" slug=object.slug %}">{{ object.title }}</a></h4>
		<p class="meta">
			{{ object.created }}| Tagged under {{ object.tags.all|join:", "}}
		</p>
			{{ object.body|truncatewords:"40"|markdown }}
			<a href="{% url "blog:post_detail" slug=object.slug%}">Read More</a>
		</div>
		{% disqus_num_replies %}
	{% endfor %}
{% endblock %}

blog/templates/blog/login.html
{% extends 'blog/login_base.html' %}
{% load bootstrap3 %}
{% block main %}
 <div align="center">
 <h1>Login to comment!</h1>

 <p>
   <ul class="nav nav-pills nav-stacked" align="center">
   {% if user.is_authenticated %}
     <li>
       <a>Hello {{ user.get_full_name|default:user.username }}!</a>
     </li>
     <li>
       <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
     </li>
   {% else %}
     <li>
       <a class="active" href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>
     </li>
     <li>
       <a class="active" href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a>
     </li>
     <li>
       <a class="active" href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">Login with Twitter</a>
     </li>
   {% endif %}
   </ul>
 </p>
 
{% endblock %}

blog/templates/blog/login_base.html
<!DOCTYPE html>
<html lang="en">
 <head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>{% block title %}Yinglei's Blog{% endblock %}</title>

   <!-- Bootstrap -->
   <link href="/static/css/bootstrap.min.css" rel="stylesheet">
   <link href="/static/css/bootstrap-theme.min.css" rel="stylesheet">
   <link href="/static/css/fbposter.css" rel="stylesheet">

   <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
   <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
   <!--[if lt IE 9]>
     <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
     <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
   <![endif]-->
 </head>
 <body>
   {% block main %}{% endblock %}
   <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
   <!-- Include all compiled plugins (below), or include individual files as needed -->
   <script src="/static/js/bootstrap.min.js"></script>
 </body>
</html>

blog/templates/blog/post.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% load django_markdown %}
{% load disqus_tags %}
{% disqus_show_comments % }

{% block blog_posts %}
<div class = "post" >
  <h4><a href="{% url "blog:post_detail" slug=object.slug %}">{{ object.title }}</a></h4>
  <p class="meta">
  	{{ object.created }}| Tagged under {{ object.tags.all|join:", "}}
  </p>
  {{ object.body|markdown }}
  <div
		class="fb-like"
		data-share="true"
		data-width="450"
		data-show-faces="true">
  </div>

  <hr>
  <hr>
    
</div>
{% endblock %}
<script type="text/javascript">
  var disqus_developer = 1;
  var disqus_url = 'http://localhost:8080';
</script>

{% disqus_dev %}

blog/templates/blog/userauth.html
{% extends 'blog/auth_base.html' %}
{% load bootstrap3 %}
{% block main %}
 <div align="center">
 <h1>Login to comment!</h1>

 <p>
   <ul class="nav nav-pills nav-stacked" align="center">
   {% if user.is_authenticated %}
     <li>
       <a>Hello {{ user.get_full_name|default:user.username }}!</a>
     </li>
     <li>
       <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
     </li>
   {% else %}
     <li>
       <a class="active" href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>
     </li>
     <li>
       <a class="active" href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a>
     </li>
     {% endif %}
   </ul>
 </p>
 
{% endblock %}